/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.10.0. DO NOT MODIFY.
*/
`default_nettype none
module tt_um_gerardvt_clash_poc
    ( // Inputs
      input wire  clk // clock
    , input wire  rst_n
    , input wire  ena // enable
    , input wire [7:0] ui_in
    , input wire [7:0] uio_in

      // Outputs
    , output wire [7:0] uo_out
    , output wire [7:0] uio_out
    , output wire [7:0] uio_oe
    );
  wire  c$bindCsr;
  wire [1:0] pat;
  wire  inv;
  wire [1:0] pal;
  wire [7:0] result_0;
  wire [0:0] c$app_arg;
  wire [0:0] c$app_arg_0;
  wire [0:0] c$app_arg_1;
  wire [0:0] c$app_arg_2;
  wire [0:0] c$app_arg_3;
  wire [7:0] c$app_arg_4;
  wire [7:0] r2;
  wire [0:0] c$app_arg_5;
  wire [7:0] c$app_arg_6;
  wire [7:0] g2;
  wire [0:0] c$app_arg_7;
  wire [7:0] c$app_arg_8;
  wire [7:0] b2;
  wire [23:0] result_1;
  wire [23:0] c$ds_case_alt;
  wire [23:0] c$ds_case_alt_0;
  wire [7:0] c$ds_app_arg;
  wire [7:0] c$ds_app_arg_0;
  wire [7:0] c$ds_app_arg_1;
  wire [7:0] result_2;
  wire [7:0] result_3;
  wire [7:0] result_4;
  wire [0:0] c$app_arg_9;
  wire [7:0] c$triWave_arg0;
  wire [7:0] c$triWave_arg0_0;
  wire [7:0] c$triWave_arg0_case_alt;
  wire [7:0] c$triWave_arg0_1;
  wire [7:0] c$triWave_arg0_case_alt_0;
  wire [7:0] c$triWave_arg0_case_alt_1;
  wire  c$triWave_arg0_case_scrut;
  wire  c$triWave_arg0_case_scrut_0;
  wire [7:0] result_5;
  wire [7:0] result_6;
  wire [7:0] i;
  wire [7:0] c$plasmaRaw_app_arg;
  wire [7:0] c$plasmaRaw_case_alt;
  wire [7:0] c$plasmaRaw_case_alt_0;
  wire [7:0] c$plasmaRaw_case_alt_1;
  wire [7:0] result_7;
  wire [7:0] result_8;
  wire [7:0] c$triWave_arg0_2;
  wire [7:0] c$triWave_arg0_case_alt_2;
  wire [7:0] c$triWave_arg0_case_alt_3;
  wire [7:0] c$triWave_arg0_app_arg;
  wire [7:0] c$triWave_arg0_3;
  wire [7:0] c$triWave_arg0_case_alt_4;
  wire [7:0] c$triWave_arg0_case_alt_5;
  wire [7:0] c$triWave_arg0_app_arg_0;
  wire [7:0] c$triWave_arg0_case_alt_6;
  wire [7:0] diag;
  wire  c$triWave_arg0_case_scrut_1;
  wire  c$triWave_arg0_case_scrut_2;
  reg [7:0] t = 8'd0;
  wire [7:0] result_9;
  wire  p;
  wire [7:0] result_10;
  wire [7:0] c$s_case_alt;
  wire [7:0] c$s_case_alt_0;
  wire [1:0] spd;
  wire [7:0] c$p_app_arg;
  wire [7:0] uiU;
  wire  c$app_arg_10;
  wire  c$app_arg_11;
  wire  c$vCount1_case_scrut;
  reg [9:0] vCount1 = 10'd0;
  wire [9:0] c$vCount1_app_arg;
  wire [9:0] c$vCount1_case_alt;
  wire  c$hCount1_case_scrut;
  reg [9:0] hCount1 = 10'd0;
  wire [9:0] c$hCount1_app_arg;
  wire [7:0] c$bv;
  wire [7:0] c$bv_0;
  wire [9:0] c$bv_1;
  wire [8:0] c$bv_2;
  wire [9:0] c$bv_3;
  wire [9:0] c$bv_4;
  wire [10:0] c$bv_5;
  wire [7:0] c$bv_6;
  wire [23:0] result;

  assign c$bindCsr = (~ rst_n);

  assign result = {result_0,   8'b00000000,
                   8'b00000000};

  assign c$bv = (uiU >> (64'sd1));

  assign pat = c$bv[0+:2];

  assign inv = (c$p_app_arg[(64'sd5)]) == (1'b1);

  assign c$bv_0 = (uiU >> (64'sd6));

  assign pal = c$bv_0[0+:2];

  assign result_0 = (~ ((hCount1 < 10'd640) & (vCount1 < 10'd480))) ? (({c$app_arg_9,(({(1'b0),(({(1'b0),(({(1'b0),(({c$app_arg_2,(3'b000)}))}))}))}))})) : (({c$app_arg_9,(({((((c$app_arg_7)))),(({((((c$app_arg_5)))),(({((((c$app_arg_3)))),(({c$app_arg_2,(({((((c$app_arg_1)))),(({((((c$app_arg_0)))),((((c$app_arg))))}))}))}))}))}))}))}));

  assign c$app_arg = ((c$app_arg_4[(64'sd1)]) == (1'b1)) ? 1'b1 : 1'b0;

  assign c$app_arg_0 = ((c$app_arg_6[(64'sd1)]) == (1'b1)) ? 1'b1 : 1'b0;

  assign c$app_arg_1 = ((c$app_arg_8[(64'sd1)]) == (1'b1)) ? 1'b1 : 1'b0;

  assign c$app_arg_2 = (c$app_arg_10);

  assign c$app_arg_3 = ((c$app_arg_4[(64'sd0)]) == (1'b1)) ? 1'b1 : 1'b0;

  assign c$app_arg_4 = (r2);

  assign r2 = result_1[23:16];

  assign c$app_arg_5 = ((c$app_arg_6[(64'sd0)]) == (1'b1)) ? 1'b1 : 1'b0;

  assign c$app_arg_6 = (g2);

  assign g2 = result_1[15:8];

  assign c$app_arg_7 = ((c$app_arg_8[(64'sd0)]) == (1'b1)) ? 1'b1 : 1'b0;

  assign c$app_arg_8 = (b2);

  assign b2 = result_1[7:0];

  assign result_1 = c$triWave_arg0_case_scrut_0 ? {c$ds_app_arg_0,
                                                   c$ds_app_arg,
                                                   result_2 >> (64'sd6)} : c$ds_case_alt;

  assign c$ds_case_alt = c$triWave_arg0_case_scrut ? {c$ds_app_arg_0,
                                                      c$ds_app_arg,
                                                      result_2 >> (64'sd6)} : c$ds_case_alt_0;

  assign c$ds_case_alt_0 = (pal == 2'd2) ? {c$ds_app_arg_0,
                                            c$ds_app_arg,   8'd0} : {c$ds_app_arg_1,
                                                                     c$ds_app_arg_1,   c$ds_app_arg_1};

  assign c$ds_app_arg = result_3 >> (64'sd6);

  assign c$ds_app_arg_0 = result_4 >> (64'sd6);

  assign c$ds_app_arg_1 = result_5 >> (64'sd6);

  assign result_2 = (c$triWave_arg0 < 8'd128) ? (c$triWave_arg0 << (64'sd1)) : ((8'd255 - c$triWave_arg0) << (64'sd1));

  assign result_3 = (c$triWave_arg0_0 < 8'd128) ? (c$triWave_arg0_0 << (64'sd1)) : ((8'd255 - c$triWave_arg0_0) << (64'sd1));

  assign result_4 = (c$triWave_arg0_1 < 8'd128) ? (c$triWave_arg0_1 << (64'sd1)) : ((8'd255 - c$triWave_arg0_1) << (64'sd1));

  assign c$app_arg_9 = (c$app_arg_11);

  assign c$triWave_arg0 = c$triWave_arg0_case_scrut_0 ? (result_5 + 8'd171) : (result_5 + 8'd213);

  assign c$triWave_arg0_0 = c$triWave_arg0_case_scrut_0 ? (result_5 + 8'd85) : c$triWave_arg0_case_alt;

  assign c$triWave_arg0_case_alt = c$triWave_arg0_case_scrut ? (result_5 + 8'd149) : c$triWave_arg0_case_alt_1;

  assign c$triWave_arg0_1 = c$triWave_arg0_case_scrut_0 ? result_5 : c$triWave_arg0_case_alt_0;

  assign c$triWave_arg0_case_alt_0 = c$triWave_arg0_case_scrut ? c$triWave_arg0_case_alt_1 : result_5;

  assign c$triWave_arg0_case_alt_1 = result_5 + 8'd64;

  assign c$triWave_arg0_case_scrut = pal == 2'd1;

  assign c$triWave_arg0_case_scrut_0 = pal == 2'd0;

  assign result_5 = inv ? (8'd255 - result_6) : result_6;

  assign c$bv_1 = (((({{(10-8) {1'b0}},result_8}) + ({{(10-8) {1'b0}},result_7})) + ({{(10-8) {1'b0}},c$plasmaRaw_app_arg})) >> (64'sd2));

  assign result_6 = c$triWave_arg0_case_scrut_2 ? (c$bv_1[0+:8]) : c$plasmaRaw_case_alt;

  assign i = c$triWave_arg0_case_alt_6 + t;

  assign c$plasmaRaw_app_arg = (i < 8'd128) ? (i << (64'sd1)) : ((8'd255 - i) << (64'sd1));

  assign c$plasmaRaw_case_alt = c$triWave_arg0_case_scrut_1 ? c$plasmaRaw_case_alt_1 : c$plasmaRaw_case_alt_0;

  assign c$plasmaRaw_case_alt_0 = (pat == 2'd2) ? c$plasmaRaw_case_alt_1 : ((c$triWave_arg0_app_arg_0 ^ c$triWave_arg0_app_arg) + t);

  assign c$bv_2 = ((({{(9-8) {1'b0}},result_8}) + ({{(9-8) {1'b0}},result_7})) >> (64'sd1));

  assign c$plasmaRaw_case_alt_1 = c$bv_2[0+:8];

  assign result_7 = (c$triWave_arg0_2 < 8'd128) ? (c$triWave_arg0_2 << (64'sd1)) : ((8'd255 - c$triWave_arg0_2) << (64'sd1));

  assign result_8 = (c$triWave_arg0_3 < 8'd128) ? (c$triWave_arg0_3 << (64'sd1)) : ((8'd255 - c$triWave_arg0_3) << (64'sd1));

  assign c$triWave_arg0_2 = c$triWave_arg0_case_scrut_2 ? c$triWave_arg0_case_alt_3 : c$triWave_arg0_case_alt_2;

  assign c$triWave_arg0_case_alt_2 = c$triWave_arg0_case_scrut_1 ? c$triWave_arg0_case_alt_3 : (c$triWave_arg0_case_alt_6 + 8'd128);

  assign c$triWave_arg0_case_alt_3 = c$triWave_arg0_app_arg + t;

  assign c$bv_3 = (vCount1 >> (64'sd1));

  assign c$triWave_arg0_app_arg = c$bv_3[0+:8];

  assign c$triWave_arg0_3 = c$triWave_arg0_case_scrut_2 ? c$triWave_arg0_case_alt_5 : c$triWave_arg0_case_alt_4;

  assign c$triWave_arg0_case_alt_4 = c$triWave_arg0_case_scrut_1 ? c$triWave_arg0_case_alt_5 : c$triWave_arg0_case_alt_6;

  assign c$triWave_arg0_case_alt_5 = c$triWave_arg0_app_arg_0 + t;

  assign c$bv_4 = (hCount1 >> (64'sd1));

  assign c$triWave_arg0_app_arg_0 = c$bv_4[0+:8];

  assign c$triWave_arg0_case_alt_6 = diag + t;

  assign c$bv_5 = ((({{(11-10) {1'b0}},hCount1}) + ({{(11-10) {1'b0}},vCount1})) >> (64'sd2));

  assign diag = c$bv_5[0+:8];

  assign c$triWave_arg0_case_scrut_1 = pat == 2'd1;

  assign c$triWave_arg0_case_scrut_2 = pat == 2'd0;

  // register begin
  always @(posedge clk or  posedge  c$bindCsr) begin : t_register
    if ( c$bindCsr) begin
      t <= 8'd0;
    end else if (ena) begin
      t <= result_9;
    end
  end
  // register end

  assign result_9 = ((c$hCount1_case_scrut & c$vCount1_case_scrut) & (~ p)) ? (t + result_10) : t;

  assign p = (c$p_app_arg[(64'sd0)]) == (1'b1);

  assign result_10 = (spd == 2'd0) ? 8'd1 : c$s_case_alt;

  assign c$s_case_alt = (spd == 2'd1) ? 8'd2 : c$s_case_alt_0;

  assign c$s_case_alt_0 = (spd == 2'd2) ? 8'd4 : 8'd8;

  assign c$bv_6 = (uiU >> (64'sd3));

  assign spd = c$bv_6[0+:2];

  assign c$p_app_arg = (uiU);

  assign uiU = ui_in;

  assign c$app_arg_10 = ((vCount1 >= 10'd490) & (vCount1 < 10'd492)) ? 1'b0 : 1'b1;

  assign c$app_arg_11 = ((hCount1 >= 10'd656) & (hCount1 < 10'd752)) ? 1'b0 : 1'b1;

  assign c$vCount1_case_scrut = vCount1 == 10'd524;

  // register begin
  always @(posedge clk or  posedge  c$bindCsr) begin : vCount1_register
    if ( c$bindCsr) begin
      vCount1 <= 10'd0;
    end else if (ena) begin
      vCount1 <= c$vCount1_app_arg;
    end
  end
  // register end

  assign c$vCount1_app_arg = c$hCount1_case_scrut ? c$vCount1_case_alt : vCount1;

  assign c$vCount1_case_alt = c$vCount1_case_scrut ? 10'd0 : (vCount1 + 10'd1);

  assign c$hCount1_case_scrut = hCount1 == 10'd799;

  // register begin
  always @(posedge clk or  posedge  c$bindCsr) begin : hCount1_register
    if ( c$bindCsr) begin
      hCount1 <= 10'd0;
    end else if (ena) begin
      hCount1 <= c$hCount1_app_arg;
    end
  end
  // register end

  assign c$hCount1_app_arg = c$hCount1_case_scrut ? 10'd0 : (hCount1 + 10'd1);

  assign uo_out = result[23:16];

  assign uio_out = result[15:8];

  assign uio_oe = result[7:0];


endmodule
`default_nettype wire

